# ,--------.      ,--.   ,--. ,--.
# '--.  .--',---.  \  `.'  /,-'  '-.
#    |  |  | .-. :  .'    \ '-.  .-'
#    |  |  \   --. /  .'.  \  |  |
#    `--'   `----''--'   '--' `--'

## => Site Settings
##############################
url: https://AyanSinhaMahapatra.github.io
baseurl: /
title: Ayan's Blog
description: >
    Ayan's Personal Website

## => Language and Timezone
##############################
lang: en
timezone: Asia/Calcutta


## => Author and Social
##############################
author:
  name: Ayan Sinha Mahapatra
  email: ayansmahapatra@gmail.com
  twitter: ayansm23
  github:  AyanSinhaMahapatra
  kaggle: ayansinhamahapatra


## => GitHub Repository (if the site is hosted by GitHub)
##############################
repository: AyanSinhaMahapatra/AyanSinhaMahapatra.github.io
repository_tree: master


## => Paths
##############################
paths:
  root: /
  home: /blog
  archive: /blog/archive.html
  portfolio: /ayan/
  gallery: /gallery/
  rss:  /feed.xml


## => Post
##############################
## excerpt
excerpt_separator: <!--more-->

## license
license: CC-BY-4.0


## => Paginate
##############################
paginate: 8
paginate_path: /blog/page:num


## => Comments
##############################
comments:
  provider: disqus
  disqus:
    shortname: ayan-3


## => Pageview
##############################
pageview:
  provider: leancloud
  leancloud:
    app_id: uAG3OhdcH8H4fxSqXLyBljA7-gzGzoHsz
    app_key: Mzf5m9skSwYVWVXhGiYMNyXs
    app_class: ThomasBlog


## => Analytics
##############################
analytics:
  provider: google
  google:
    tracking_id: UA-92651501-2


## => Build
##############################
markdown: kramdown
highlighter: rouge
permalink: date

exclude:
  - CHANGELOG.md
  - CHECKLIST.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  - /test
  - /vendor

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      license: true
      aside:
        toc: true
      show_edit_on_github: true
      show_subscribe: true
      pageview: true


## => Plugins
##############################
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jemoji


## => Server
##############################
server_url: "0.0.0.0"
port: 4001